// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjziogfutzmodyqvzbfd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqemlvZ2Z1dHptb2R5cXZ6YmZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0OTkyMjQsImV4cCI6MjA3MTA3NTIyNH0.3xn95U1szfXviPR6_2O5QK6wFLyoIMCLY7ubx77Wuj0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});